# version of docker compose
version: '3.4'

# networks on which the services are going to run on
networks:
  dev:
    driver: bridge

services: # individual services
  write_api: # write API application
    depends_on: ["postgres_db"] # depends on the database service
    container_name: write_api
    ports: ["8080:80"] # exposes port 80 under alias 8080
    build: # build the dockerfile inside this directory before starting it
      context: WriteApi
      dockerfile: Dockerfile
    environment: # environment vars for dynamic configuration (no need to hardcode anywhere else)
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=postgres_db;Port=5432;Database=eshop;IntegratedSecurity=true;
      - ASPNETCORE_URLS=http://+:80
    networks: [dev] # connected to the dev network
    
  postgres_db: # database
    image: postgres:latest # use the latest postgres image from dockerhub
    container_name: postgres_db
    environment: # environment vars for configuration of db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eshop
    ports: ["5433:5432"] # exposes port 5432 under alias 5433
    restart: always # always restart in case of failure
    volumes: # store persistent data on the app_data volume
      - app_data:/var/lib/postgresql/data # physical location of the volume
    networks: [dev] # connected to the dev network
    
# volumes (actual local storage that will be used by containers for persistent data)
volumes: 
  app_data:
